package model

// BaseRole 英雄基础表。
type BaseRole struct {
	RoleId             int     `json:"roleId"`
	BRoleId            int     `json:"bRoleId"`
	NextRoleId         int     `json:"nextRoleId"`
	RoleName           string  `json:"roleName"`
	SkinId             int     `json:"skinId"`
	RoleNo             string  `json:"roleNo"`
	CnRoleNo           string  `json:"cnRoleNo"`
	EffNo              string  `json:"effNo"`
	WqNo               string  `json:"wqNo"`
	RoleElement        int     `json:"roleElement"`
	RoleProfession     int     `json:"roleProfession"`
	RoleQuality        int     `json:"roleQuality"`
	RoleDesc           string  `json:"roleDesc"`
	Skill              string  `json:"skill"`
	SkillExtra         string  `json:"skillExtra"`
	SkillPassive       string  `json:"skillPassive"`
	SkillTalentStunt   int     `json:"skillTalentStunt"`
	SkillTalentPassive string  `json:"skillTalentPassive"`
	StarPassive        string  `json:"starPassive"`
	StarTalentPassive  string  `json:"starTalentPassive"`
	Attack             int     `json:"attack"`
	HpMax              int     `json:"hpMax"`
	Mp                 int     `json:"mp"`
	Armor              int     `json:"armor"`
	Speed              int     `json:"speed"`
	SkillDamageR       float32 `json:"skillDamageR"`
	Hit                float32 `json:"hit"`
	Dodge              float32 `json:"dodge"`
	Crit               float32 `json:"crit"`
	CritR              float32 `json:"critR"`
	ReduceArmorR       float32 `json:"reduceArmorR"`
	ImmuneR            float32 `json:"immuneR"`
	ReduceDamageR      float32 `json:"reduceDamageR"`
	CcDamage           float32 `json:"ccDamage"`
	IsTp               int     `json:"isTp"`
	MHeight            int     `json:"m_height"`
	HasPet             int     `json:"hasPet"`
	RoleMoveDis1       float32 `json:"roleMoveDis1"`
	RoleMoveDis2       float32 `json:"roleMoveDis2"`
	RoleBackDis        float32 `json:"roleBackDis"`
	RoleHpcDis         float32 `json:"roleHpcDis"`
	IsRegular          int     `json:"is_regular"`
	IsReliveInt        int     `json:"isReliveint"`
	InitialCombat      int     `json:"initialCombat"`
	IsPuppet           int     `json:"isPuppetINT"`
	IsT0               int     `json:"isT0"`
	TagIds             string  `json:"tagIds"`
	IsPlay             int     `json:"isPlay"`
	IsAnger            int     `json:"isAnger"`
	CombatRate         float32 `json:"combatRate"`
	ZhpMax             int     `json:"zhpMax"`
	ZAttack            int     `json:"ZAttack"`
	ZRrit              int     `json:"ZRrit"`
	ZRritR             int     `json:"ZRritR"`
	ZreduceArmorR      int     `json:"zreduceArmorR"`
}
